<MyWidget>:
    FloatLayout:
        Button:
            text: "Clock In"
            size_hint: None, None
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            size: 200, 50
            on_press: root.on_button_click()

    FloatLayout:
        Button:
            text: "Clock Out"
            size_hint: None, None
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            size: 200, 50
            on_press: root.on_button_click2()
